name: Terraform Validation and CI/CD Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # Run Super Linter to validate code quality and enforce style guidelines
  superlinter:
    name: Run Super Linter for Code Quality and Style Enforcement
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Validate and lint Terraform configuration to ensure proper syntax, code quality, and security best practices
  terraform:
    name: Validate and Lint Terraform Configuration for Quality and Security
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Configure Kubernetes using KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > $HOME/.kube/microk8s-config

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Execute TFLint for Terraform Code Linting
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.53.0

      - name: Perform Terraform Linting
        run: tflint --format=compact

      - name: Execute TFSEC for Security Scanning of Terraform Code
        uses: aquasecurity/tfsec-action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Uncomment the following steps if integrating Terraform's `plan` and `apply` stages into your CI/CD pipeline.
# The Terraform Plan step will run on pull requests to review proposed changes before merging.
# The Terraform Apply step will automatically apply changes when pushing to the `main` branch.
# Ensure cluster access permissions and security policies allow safe remote management.

#        - name: Terraform Plan (Run on Pull Request)
#          run: terraform plan -no-color
#          if: github.event_name == 'pull_request'
#
#        - name: Terraform Apply (Run on Push to Main)
#          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
#          run: terraform apply -auto-approve
