name: Terraform Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  superlinter:
    name: Run Super Linter for Code Validation
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Lint Code
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: "main"
          DISABLE_ERRORS: false
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: true
          VALIDATE_JSON: true
          VALIDATE_MD: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  terraform:
    name: Validate and Lint Terraform Configuration
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Configure Kubernetes using KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" | base64 --decode > $HOME/.kube/microk8s-config

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Configuration
        run: terraform validate

      - name: Execute TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.53.0

      - name: Perform Terraform Linting
        run: tflint --format=compact

      - name: Execute TFSEC
        uses: aquasecurity/tfsec-action@v1.0.3